version: '3.3'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
      dockerfile: Dockerfile.nginx
    ports:
      - "9000:80"
    links:
      - frontend
      - api

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./scripts/await-modules.sh -- npm run dev
    depends_on:
      - npm
    expose:
      - "8080"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./scripts/await-modules.sh -- npm start
    depends_on:
      - npm
    expose:
      - "3000"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume

  npm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "rm node_modules/.ready; npm install && touch node_modules/.ready"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume

volumes:
  node_modules:
