version: '3.3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./scripts/await-modules.sh -- npm run dev
    depends_on:
      - npm
    ports:
      - "8080:8080"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./scripts/await-modules.sh -- npm start
    depends_on:
      - npm
    ports:
      - "3000:3000"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume
  npm:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: /bin/bash -c "rm node_modules/.ready; npm install && touch node_modules/.ready"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume
volumes:
  node_modules:
