version: '3.3'
services:
  proxy:
    restart: always
    build:
      context: ./services/proxy
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    links:
      - frontend
      - api

  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: web_anon
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    expose:
      - "3000"
    links:
      - postgres
    environment:
      PGRST_DB_URI: postgres://web_anon:mysecretpassword@postgres:5432/app_db
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: web_anon

  frontend:
    build:
      context: .
      dockerfile: ./services/app/Dockerfile
    command: /bin/bash -c "npm install && npm run dev"
    expose:
      - "8080"
    volumes:
      - source: .
        target: /usr/src/elm-slides
        type: bind
      - source: node_modules
        target: /usr/src/elm-slides/node_modules
        type: volume

volumes:
  db-data:
  node_modules:
